ProxySQL compilation is failing on CentOS 7 due to below Error:
checking whether compiler supports -Wall... Can't locate IPC/Cmd.pm in @INC (@INC contains: /tmp/proxysql/deps/libssl/openssl-openssl-3.0.2/util/perl /opt/rh/devtoolset-8/root//usr/lib64/perl5/vendor_perl /opt/rh/devtoolset-8/root/usr/lib/perl5 /opt/rh/devtoolset-8/root//usr/share/perl5/vendor_perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /tmp/proxysql/deps/libssl/openssl-openssl-3.0.2/external/perl/Text-Template-1.56/lib) at /tmp/proxysql/deps/libssl/openssl-openssl-3.0.2/util/perl/OpenSSL/config.pm line 18.
BEGIN failed--compilation aborted at /tmp/proxysql/deps/libssl/openssl-openssl-3.0.2/util/perl/OpenSSL/config.pm line 18.
Compilation failed in require at /tmp/proxysql/deps/libssl/openssl/Configure line 23.
BEGIN failed--compilation aborted at /tmp/proxysql/deps/libssl/openssl/Configure line 23.
make[1]: *** [libssl/openssl/libssl.a] Error 2
make[1]: *** Waiting for unfinished jobs....

Solution:
Installed the missing perl module perl-IPC-Cmd